name: Release New Version and publish
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Detect what files changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            js:
              - '**/*.[tj]{s,sx}'
              - 'package.json'
      - uses: actions/setup-node@v3
        if: steps.changes.outputs.js == 'true'
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        if: steps.changes.outputs.js == 'true'
        run: yarn install
      - name: Release
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
